name: Lint & Test
on: push

concurrency: 
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Init & Build
        uses: ./.github/actions/build

      - name: Run lint
        run: pnpm lint
      

      - name: Run unit tests
        run: pnpm test:jest